server:
  port : 8080
spring:
  datasource:
    url: jdbc:postgresql://dpg-cgtrg3d269vbmevggnr0-a.singapore-postgres.render.com:5432/hafaly
    username: hafaly_user
    password: Yagqv56XrJTOsEWBHxqdVOZwbo6hmIjS
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  file:
    name: hafaly.log
logging:
  pattern:
    console: logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %c{2} - %m%n
