server:
  port : 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hafaly
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  file:
    name: hafaly.log
  config:
    import: classpath:config.yml
  main:
    allow-circular-references=true:
