server:
  port : 8080
spring:
  datasource:
    url: jdbc:postgresql://dpg-cisah45ph6et1sed8680-a.oregon-postgres.render.com:5432/hafaly_vcz6
    username: hafaly_vcz6_user
    password: 7WzywwVGZCgCwpoXKlofNRKGGeH4nScI
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  file:
    name: hafaly.log
logging:
  pattern:
    console: logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p [%t] %c{2} - %m%n
